### ISSUE TITLE
[설정] 스토리북 v.6 => v.7

### ISSUE THREAD

**Issue by hyunwleeee** [NatureTeam/NatureKarly#10]

**Comment by hyunwleeee** [comment]
# Issue: setting

## 구현 세부 사항
- [x] storybook v6 => v7

## 관련 이슈 📎 (option)



## 기능 구현 관련 정보 (option)

**Comment by BORAVORAYOON** [comment]
pull 받은 후 정삭적으로 작동합니다.

**Comment by nahee09** [comment]
pull 받은 후 정상적으로 작동합니다.

**Comment by semin99** [comment]
pull 받은 후 정상적으로 작동합니다.
