### ISSUE TITLE
🐞 Bug: eslint 빨간줄 뜨는 문제

### ISSUE THREAD

**Issue by nahee09** [NatureTeam/NatureKarly#12]
# Issue: 버그 보고
> - 필수 내용: 

문제 상황: 온통 빨간 줄이 뜹니다. 
에러 메시지: Expectied linebreaks to be 'LF' but found 'CRLF' 

## 📈 버그가 발생하는 페이지(파일)와 문제점
모든 파일에서 빨간 줄이 뜹니다.

### 스크린샷
![image](https://user-images.githubusercontent.com/119389649/224588319-a0ef8104-d4fe-446f-842a-5b1c6764bb70.png)

## 버그가 없을 때의 동작 설명
빨간 줄이 뜨지 않아야 합니다. 

## 🏀 해결방안 (Solution)
1. .eslintrc.js 파일 안 rules에 아래 코드 추가

`'prettier/prettier': ['error', { endOfLine: 'auto' }]`

2. plugins에 'prettier'추가

`plugins: ['react', 'import', 'react-hooks', 'jsx-a11y', 'html', 'prettier']`

[참고](https://velog.io/@jakeseo_me/LF%EC%99%80-CRLF%EC%9D%98-%EC%B0%A8%EC%9D%B4-Feat.-Prettier)

**Comment by BORAVORAYOON** [comment]
pull 받았습니다.

**Comment by semin99** [comment]
pull 받은 후 정상적으로 작동합니다.
