### ISSUE TITLE
🐞 Bug: 스토리북 절대경로 인식 안되는 현상 수정

### ISSUE THREAD

**Issue by semin99** [NatureTeam/NatureKarly#41]
# Issue: 버그 보고
> - 필수 내용: 문제 상황, 코드, 에러 메시지, 이슈 번호(해결한 경우)
> - 선택 사항: 이미지, 동영상, 참고 링크
![image](https://user-images.githubusercontent.com/87403695/225666661-0788afc6-7f95-4c5b-b1bd-8ccbbb15d1ea.png)
절대경로가 인식이 안되는 버그 현상

## 📈 버그가 발생하는 페이지(파일)와 문제점

vite.config.js 파일에서 resolve 부분을 수정해야합니다.

### 수정전

```
import { resolve } from 'node:path';
....
  resolve: {
    alias: [{ find: '@', replacement: resolve(__dirname, './src') }],
  },
.....

```

### 수정후

```
import * as path from 'node:path';
.....
  resolve: {
    alias: {
      '@': path.resolve(__dirname, './src'),
    },
  },
.....

```

**Comment by hyunwleeee** [comment]
우리조 ACE 세민님...

**Comment by semin99** [comment]
> 우리조 ACE 세민님...

이거 해결한다고 하루가 사라졌네요...ㅎ
